apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: my-app
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: my-volume
          mountPath: /app
  volumes:
    - name: my-volume
      emptyDir: {}
